import os

from dotenv import load_dotenv

from src.constants.vars import (
    APP_VIEW_ROUTE_NAME,
    AUTH_BLUEPRINT_ROUTE_NAME,
    AUTH_VIEW_ROUTE_NAME,
    BLUEPRINT_AUTH_PATH,
    BLUEPRINT_NOTES_PATH,
    NOTES_BLUEPRINT_ROUTE_NAME,
    VIEW_APP_PATH,
    VIEW_AUTH_PATH,
)

load_dotenv()


class DefaultConfig:
    TZ = os.getenv("TZ", "America/Argentina/Buenos_Aires")

    SECRET_KEY = os.getenv("SECRET_KEY", "supersecret")
    HOST = os.getenv("HOST", "0.0.0.0")
    PORT = int(os.getenv("PORT", "5000"))
    MAX_CONTENT_LENGTH = int(os.getenv("MAX_CONTENT_LENGTH", str(1 * 1024 * 1024)))

    MYSQL_HOST = os.getenv("MYSQL_HOST")
    MYSQL_USER = os.getenv("MYSQL_USER")
    MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")
    MYSQL_PORT = os.getenv("MYSQL_PORT", 3306)
    MYSQL_DB_NAME = os.getenv("MYSQL_DB_NAME")
    SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DB_NAME}"

    SQLALCHEMY_TRACK_MODIFICATIONS = False

    LOGIN_ROUTE = f"{AUTH_BLUEPRINT_ROUTE_NAME}.login"
    LOGOUT_ROUTE = f"{AUTH_BLUEPRINT_ROUTE_NAME}.logout"
    SIGN_UP_ROUTE = f"{AUTH_BLUEPRINT_ROUTE_NAME}.sign_up"
    GET_ALL_NOTES_ROUTE = f"{NOTES_BLUEPRINT_ROUTE_NAME}.get_all"
    CREATE_NOTE_ROUTE = f"{NOTES_BLUEPRINT_ROUTE_NAME}.create"
    DELETE_NOTE_ROUTE = f"{NOTES_BLUEPRINT_ROUTE_NAME}.delete"
    EDIT_NOTE_ROUTE = f"{NOTES_BLUEPRINT_ROUTE_NAME}.edit"

    LOGIN_ROUTE_PATH = f"{BLUEPRINT_AUTH_PATH}/login"
    LOGOUT_ROUTE_PATH = f"{BLUEPRINT_AUTH_PATH}/logout"
    SIGN_UP_ROUTE_PATH = f"{BLUEPRINT_AUTH_PATH}/sign_up"
    GET_ALL_NOTES_ROUTE_PATH = BLUEPRINT_NOTES_PATH
    CREATE_NOTE_ROUTE_PATH = f"{BLUEPRINT_NOTES_PATH}/create"
    DELETE_NOTE_ROUTE_PATH = f"{BLUEPRINT_NOTES_PATH}/delete"
    EDIT_NOTE_ROUTE_PATH = f"{BLUEPRINT_NOTES_PATH}/edit"

    LOGIN_VIEW = f"{AUTH_VIEW_ROUTE_NAME}.login"
    SIGN_UP_VIEW = f"{AUTH_VIEW_ROUTE_NAME}.sign_up"
    HOME_VIEW = f"{APP_VIEW_ROUTE_NAME}.home"

    LOGIN_VIEW_PATH = f"{VIEW_AUTH_PATH}/login"
    SIGN_UP_VIEW_PATH = f"{VIEW_AUTH_PATH}/sign_up"
    HOME_VIEW_PATH = f"{VIEW_APP_PATH}/home"

    DEBUG = False
    TESTING = False

    CHECK_CONNECTIONS = True
