# ##### FLASH #####
FLASH_SUCCESS = "success"
FLASH_ERROR = "error"

# ##### SUCCESS #####
CODE_SUCCESS_HEALTH = "SUCCESS_HEALTH"
CODE_SUCCESS_READY = "SUCCESS_READY"
CODE_SUCCESS_GET_ALL_NOTES = "SUCCESS_GET_ALL_NOTES"
CODE_SUCCESS_ADD_NOTE = "SUCCESS_ADD_NOTE"
CODE_SUCCESS_DELETE_NOTE = "SUCCESS_DELETE_NOTE"
CODE_SUCCESS_EDIT_NOTE = "SUCCESS_EDIT_NOTE"
CODE_SUCCESS_LOGGED_IN = "SUCCESS_LOGGED_IN"
CODE_SUCCESS_LOGOUT = "SUCCESS_LOGOUT"
CODE_SUCCESS_SIGN_UP = "SUCCESS_SIGN_UP"

# ##### ERROR #####
CODE_ERROR_INTERNAL_SERVER = "ERROR_INTERNAL_SERVER"
CODE_ERROR_DATABASE = "ERROR_DATABASE"
CODE_ERROR_GENERIC = "ERROR_GENERIC"

# ##### NOT_VALID #####
CODE_NOT_VALID_INTEGER = "NOT_VALID_INTEGER"
CODE_NOT_VALID_FIELDS = "NOT_VALID_FIELDS"
CODE_NOT_VALID_PASSWORD = "NOT_VALID_PASSWORD"

# ##### NOT_EXISTS #####

# ##### ALREADY_EXISTS #####
CODE_ALREADY_EXISTS_NOTE = "ALREADY_EXISTS_NOTE"
CODE_ALREADY_EXISTS_USER = "ALREADY_EXISTS_USER"

# ##### NOT_FOUND #####
CODE_NOT_FOUND_ROUTE = "NOT_FOUND_ROUTE"
CODE_NOT_FOUND_NOTE = "NOT_FOUND_NOTE"
CODE_NOT_FOUND_USER = "NOT_FOUND_USER"
