# FLASH CODES
FLASH_SUCCESS = "success"
FLASH_ERROR = "error"

# RESPONSE CODES
CODE_CREATE_NOTE = "CREATE_NOTE"
CODE_DELETE_NOTE = "DELETE_NOTE"
CODE_EDIT_NOTE = "EDIT_NBOTE"

CODE_SUCCESFULLY_LOGGED_IN = "SUCCESFULLY_LOGGED_IN"
CODE_SUCCESFULLY_LOGOUT = "SUCCESFULLY_LOGOUT"
CODE_SUCCESFULLY_SIGN_UP = "SUCCESFULLY_SIGN_UP"

CODE_ALREADY_USER_EXISTS = "ALREADY_USER_EXISTS"

CODE_NOT_EXISTS_NOTE = "NOT_NOTE_EXISTS"
CODE_NOT_VALID_FIELDS = "NOT_VALID_FIELDS"
CODE_NOT_EXISTS_USER = "NOT_USER_EXISTS"
CODE_NOT_VALID_PASSWORD = "NOT_VALID_PASSWORD"
CODE_NOT_VALID_ID = "NOT_VALID_ID"

CODE_ERROR_API = "ERROR_INTERNAL_SERVER"
CODE_ERROR_DATABASE = "ERROR_DATABASE"
CODE_ERROR_GENERIC = "ERROR_GENERIC"
CODE_ERROR_DELETE_NOTE = "ERROR_DELETE_NOTE"
CODE_ERROR_UPDATE_NOTE = "ERROR_UPDATE_NOTE"
