# FOLDER NAMES
STATIC_FOLDER_NAME = "static"

CSS_FOLDER_NAME = "css"
SCSS_FOLDER_NAME = "scss"
JS_FOLDER_NAME = "js"
TS_FOLDER_NAME = "ts"

GENERAL_TEMPLATES_FOLDER_NAME = "templates"
AUTH_TEMPLATES_FOLDER_NAME = "auth"
APP_TEMPLATES_FOLDER_NAME = "app"

# VERSIONS
VERSION_VIEWS = "v1"
VERSION_BLUEPRINTS = "v1"

# ROUTE NAMES
AUTH_BLUEPRINT_ROUTE_NAME = "auth"
NOTES_BLUEPRINT_ROUTE_NAME = "notes"

AUTH_VIEW_ROUTE_NAME = "auth_view"
APP_VIEW_ROUTE_NAME = "app_view"

# BLUEPRINTS PATHS

PREFIX_BLUEPRINTS_PATH = f"/api/{VERSION_BLUEPRINTS}"
BLUEPRINT_AUTH_PATH = f"{PREFIX_BLUEPRINTS_PATH}/auth"
BLUEPRINT_NOTES_PATH = f"{PREFIX_BLUEPRINTS_PATH}/notes"

PREFIX_VIEWS_PATH = f"/views/{VERSION_VIEWS}"
VIEW_AUTH_PATH = f"{PREFIX_VIEWS_PATH}/auth"
VIEW_APP_PATH = f"{PREFIX_VIEWS_PATH}/app"

# TEMPLATE NAMES
TEMPLATE_LOGIN_NAME = "login.html"
TEMPLATE_SIGN_UP_NAME = "sign_up.html"
TEMPLATE_HOME_NAME = "home.html"
