##### FOLDER NAMES #####
STATIC_FOLDER_NAME = "static"

CSS_FOLDER_NAME = "css"
SCSS_FOLDER_NAME = "scss"

GENERAL_TEMPLATES_FOLDER_NAME = "templates"
AUTH_TEMPLATES_FOLDER_NAME = "templates"
APP_TEMPLATES_FOLDER_NAME = "templates"

GENERAL_VIEWS_FOLDER_NAME = "views"
AUTH_VIEWS_FOLDER_NAME = "auth"
APP_VIEWS_FOLDER_NAME = "app"

##### VERSIONS #####
VERSION_VIEWS = "v1"
VERSION_BLUEPRINTS = "v1"

##### ROUTE NAMES #####
AUTH_BLUEPRINT_ROUTE_NAME = "auth_route"
NOTES_BLUEPRINT_ROUTE_NAME = "notes_route"

AUTH_VIEW_ROUTE_NAME = "auth_views"
APP_VIEW_ROUTE_NAME = "app_views"

##### BLUEPRINTS PATHS #####

PREFIX_BLUEPRINTS_PATH = f"/{VERSION_BLUEPRINTS}/api"
BLUEPRINT_AUTH_PATH = f"{PREFIX_BLUEPRINTS_PATH}/auth"
BLUEPRINT_NOTES_PATH = f"{PREFIX_BLUEPRINTS_PATH}/notes"

PREFIX_VIEWS_PATH = f"/{VERSION_VIEWS}/views"
VIEW_AUTH_PATH = f"{PREFIX_VIEWS_PATH}/auth"
VIEW_APP_PATH = f"{PREFIX_VIEWS_PATH}/app"

##### FLASH CODES #####
FLASH_SUCCESS = "success"
FLASH_ERROR = "error"

##### RESPONSE CODES #####
CODE_CREATE_NOTE = "NOTE_CREATE"
CODE_DELETE_NOTE = "NOTE_DELETE"
CODE_EDIT_NOTE = "NOTE_EDIT"

CODE_SUCCESFULLY_LOGGED_IN = "SUCCESFULLY_LOGGED_IN"
CODE_SUCCESFULLY_LOGOUT = "SUCCESFULLY_LOGOUT"
CODE_SUCCESFULLY_SIGN_UP = "SUCCESFULLY_SIGN_UP"

CODE_ALREADY_USER_EXISTS = "ALREADY_USER_EXISTS"

CODE_NOT_EXISTS_NOTE = "NOT_NOTE_EXISTS"
CODE_NOT_VALID_FIELDS = "NOT_VALID_FIELDS"
CODE_NOT_EXISTS_USER = "NOT_USER_EXISTS"
CODE_NOT_VALID_PASSWORD = "NOT_VALID_PASSWORD"
CODE_NOT_VALID_ID = "NOT_VALID_ID"

CODE_ERROR_DELETE_NOTE = "ERROR_UPDATE_NOTE"
CODE_ERROR_UPDATE_NOTE = "ERROR_UPDATE_NOTE"

##### RESPONSE MESSAGES #####
MESSAGE_CREATE_NOTE = "You created a new note successfully."
MESSAGE_DELETE_NOTE = "You successfully deleted a note."
MESSAGE_EDIT_NOTE = "You successfully edited a note."

MESSAGE_SUCCESFULLY_LOGGED_IN = "You have successfully logged in."
MESSAGE_SUCCESFULLY_LOGOUT = "You have successfully disconnected."
MESSAGE_SUCCESFULLY_SIGN_UP = "Your account was successfully created."

MESSAGE_ALREADY_USER_EXISTS = "The entered email or username already exists."

MESSAGE_NOT_EXISTS_NOTE = "The note does not exist."
MESSAGE_NOT_VALID_FIELDS = "You must enter valid fields."
MESSAGE_NOT_EXISTS_USER = "The user does not exist."
MESSAGE_NOT_VALID_PASSWORD = "The password is invalid."
MESSAGE_NOT_VALID_ID = "A valid ID is required."

MESSAGE_ERROR_DELETE_NOTE = "An error occurred while editing a note."
MESSAGE_ERROR_UPDATE_NOTE = "An error occurred while editing a note."
